apiVersion: v1
kind: Service
metadata:
  name: svc-app01
  namespace: default
spec:
  selector:
    app: pod-app01
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: svc-app01
  namespace: default
spec:
  rules:
  - host: traefik.www.test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: svc-app01
          servicePort: http

