apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:v51.5.7
      ports:
        - containerPort: 3306
          hostPort: 3306
          name: mysql
      securityContext:
        privileged: true
      env:
        - name: MYSQL_ROOT_PASSWORD
          # Change this password!
          value: "TYwy2016720"
      resources:
          limits:
            cpu: 100m
      volumeMounts:
        - name: mysql-nfs
          mountPath: "/var/lib/mysql"
  volumes:
    - name: mysql-nfs
      nfs:
        server: 139.196.16.67
        path: "/nfs_file/mysqldata"