apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/mysql:5.7
      ports:
        - containerPort: 3306
          name: mysql
      securityContext:
        privileged: true
      env:
        - name: MYSQL_ROOT_PASSWORD
          # Change this password!
          value: "123456"
      resources:
        limits:
          cpu: 0.5
      volumeMounts:
        - name: mysql-nfs
          mountPath: "/var/lib/mysql"

  volumes:
    - name: mysql-nfs
      nfs:
        server: 192.168.27.134
        path: "/mnt/nfs_file/mysqldata"