apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
  labels:
    app: nginx-phpfpm
spec:
  containers:
    - name: nginx
      image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/nginx_51tywy:v1.0
      ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
      volumeMounts:
        - name: nfs
          mountPath: "/usr/share/nginx/html"
    - name: php
      image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/php:51tywy
      ports:
        - containerPort: 9000
      volumeMounts:
        - name: nfs
          mountPath: "/usr/share/nginx/html"

  volumes:
    - name: nfs
      nfs:
        server: 139.196.16.67
        path: "/nfs_file/sites/51tywy"