apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
  labels:
    app: nginx-phpfpm
spec:
  containers:
    - name: nginx
      image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/nginx_51tywy:v1.0
      ports:
        - containerPort: 80
          hostPort: 80
      volumeMounts:
        - name: nfs
          mountPath: "/usr/share/nginx/html"
    - name: php
      image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/php:51tywy
      ports:
        - containerPort: 9000
      volumeMounts:
        - name: nfs
          mountPath: "/usr/share/nginx/html"

  volumes:
    - name: nfs
      nfs:
        server: 192.168.27.134
        path: "/mnt/nfs_file/site"