apiVersion: v1
kind: Pod
metadata:
  labels:
    name: busybox
    role: master
  name: busybox
spec:
  containers:
    - name: busybox
      image: gcr.io/google_containers/busybox:1.24  
      command:
      - sleep
      - "360000"