apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v8
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v8
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v8
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v8
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: index.tenxcloud.com/google_containers/etcd:2.0.9
        securityContext:
          privileged: true
        command:
        - /usr/local/bin/etcd
        - -data-dir
        - /var/etcd/data
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
        volumeMounts:
        - name : etcd-storage
          mountPath: /var/etcd/data
      - name: kube2sky 
        image: index.tenxcloud.com/google_containers/kube2sky:1.11
        args:
        - "--kube_master_url=http://139.196.48.36:8080"
        # "--etcd-server=https://localhost:4001"
        - "-domain=cluster.local"
      - name: skydns
        image: index.tenxcloud.com/google_containers/skydns:2015-03-11-001
        command:
        - /skydns
        args:
        - "-machines=http://localhost:4001"
        - "-addr=0.0.0.0:53"
        - "-domain=cluster.local."
        # "-nameservers=10.254.200.200:53"
        ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default
