apiVersion: v1
kind: Pod
metadata:
  name: golang
  labels:
    name: golang
spec:
  containers:
    - name: golang
      image: golang:1.6-onbuild
      ports:
        - containerPort: 8080
          name: golang