apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: golang-anooc
  name: golang-anooc
spec:
  replicas: 2
  selector:
    name: golang-anooc
  template:
    metadata:
      labels:
        name: golang-anooc
    spec:
      containers:
        - name: anooc-image
          image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/golang-production-anooc:1.6.8
          ports:
            - containerPort: 80
              name: http
