apiVersion: v1
kind: Service
metadata:
    name: golang-anooc
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30005
      protocol: TCP
  selector:
     name: golang-anooc
