apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: heapster
  name: heapster
spec:
  replicas: 1
  selector:
    name: heapster
  template:
    metadata:
      labels:
        name: heapster
    spec:
      containers:
        - name: heapster
          image: index.tenxcloud.com/google_containers/heapster:v0.17.0
          command:
            - /heapster
            - --source=kubernetes:http://139.196.48.36:8080?inClusterConfig=false&kubeletHttps=true&kubeletPort=10250&useServiceAccount=true&auth=
            - --sink=influxdb:http://monitoring-influxdb:8086