apiVersion: v1
kind: Service
metadata:
    name: php-zhongdongfei
spec:
  type: NodePort
  ports:
    - name: http
      targetPort: 80
      port: 80 
      nodePort: 30014
      protocol: TCP
    - name: https
      targetPort: 443
      port: 443
      nodePort: 30015
      protocol: TCP    
  selector:
      app: nginx-phpfpm-zhongdongfei
