apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx-ingress
spec:
  replicas: 1
  selector:
    app: pod-nginx-ingress
    version: v1
  template:
    metadata:
      labels:
          app: pod-nginx-ingress
          version: v1
    spec:
      containers:
        - name: nginx
          image: index.tenxcloud.com/google_containers/nginx-ingress:0.1
          ports:
            - containerPort: 80
              name: http
              hostPort: 80
