apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-rbd
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.122.149:6789
  adminId: admin
  adminSecretName: ceph-secret-kube
  adminSecretNamespace: "default"
  pool: kube
  userId: kube
  userSecretName: ceph-secret-kube
