apiVersion: v1
kind: Service
metadata:
    name: img-server-server
spec:
  type: NodePort
  ports:
    - name: http
      targetPort: 80
      port: 80 
      nodePort: 30010
      protocol: TCP
    - name: https
      targetPort: 443
      port: 443
      nodePort: 30011
      protocol: TCP    
  selector:
      app: img-server
