apiVersion: v1
kind: ReplicationController
metadata:
  labels:
      name: img-server
  name: img-server
spec:
  replicas: 2
  selector:
      app: img-server
  template:
    metadata:
      labels:
          app: img-server
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          volumeMounts:
            - name: nfs
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: nfs
          nfs:
            server: 139.196.16.67
            path: "/nfs_file/img"
