apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: grafana
    kubernetes.io/cluster-service: "true"
  name: grafana
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    name: grafana