apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    name: influxdb
  template:
    metadata:
      labels:
        name: influxdb
    spec:
      containers:
        - name: influxdb
          image: index.tenxcloud.com/tenxcloud/influxdb:latest
          ports:
            - containerPort: 8083
              hostPort: 8083
            - containerPort: 8086
              hostPort: 8086
          env:
            - name: INFLUXDB_HOST
              value: monitoring-influxdb