apiVersion: v1
kind: Service
metadata:
    name: www-yyang-net-cn-svc
spec:
  type: NodePort
  ports:
    - name: http
      targetPort: 80
      port: 80 
      nodePort: 30017
      protocol: TCP
    - name: https
      targetPort: 443
      port: 443
      nodePort: 30018
      protocol: TCP    
  selector:
    app: www.yyang.net.cn-pod-app
