apiVersion: v1
kind: Service
metadata:
  name: pxc-service
  labels:
    app: pxc-app
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - name: "mysql"
      port: 3306
      targetPort: 3306
      nodePort: 30001
      protocol: TCP
    - name: "proxyadm"
      port: 6032
      targetPort: 6032
      nodePort: 30002
      protocol: TCP
  # label keys and values that must match in order to receive traffic for this service
  selector:
    front: proxysql
