apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      containers:
        - name: master
          image: redis:3.2.5
          ports:
            - containerPort: 6379
          env:
            - name: GET_HOSTS_FROM
              value: env
          command: ["redis-server", "--appendonly","yes","--requirepass","anooczhg123456"]
