apiVersion: v1
kind: ReplicationController
metadata:
  name: php-fpm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
      - name: php-fpm
        image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/php
        ports:
        - containerPort: 9000