apiVersion: v1
kind: Service
metadata:
  name: php-nginx-svc
  labels:
    app: php-nginx
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 80
      protocol: TCP
  selector:
    app: php-nginx