apiVersion: v1
kind: ReplicationController
metadata:
  name: php-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php-nginx
    spec:
      containers:
      - name: php-nginx
        image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nfs
          mountPath: "/usr/share/nginx/html"