apiVersion: v1
kind: ReplicationController
metadata:
  labels:
      name: img-server
  name: img-server
spec:
  replicas: 2
  selector:
      app: img-server
  template:
    metadata:
      labels:
          app: img-server
    spec:
      containers:
        - name: nginx
          image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/imgserver:1.0.2
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          volumeMounts:
            - name: nfs
              mountPath: "/opt/www/hdimage"
      volumes:
        - name: nfs
          nfs:
            server: 127.0.0.1
            path: "/nfs_file/img"
